"""add_available_slots

Revision ID: 86fba1c15676
Revises: 0c7031be1700
Create Date: 2026-06-05 21:07:20.123539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fba1c15676'
down_revision: Union[str, Sequence[str], None] = '0c7031be1700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('slot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('slot_hour', sa.Integer(), nullable=True),
    sa.Column('slot_minute', sa.Integer(), nullable=True),
    sa.Column('reserved_for_student_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reserved_for_student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_slots_id'), 'available_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_available_slots_id'), table_name='available_slots')
    op.drop_table('available_slots')
    # ### end Alembic commands ###
