"""add_homework_deadline_notified_flags

Revision ID: 0c7031be1700
Revises: 653158fede13
Create Date: 2026-05-31 13:08:22.774639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7031be1700'
down_revision: Union[str, Sequence[str], None] = '653158fede13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('notified_24h', sa.Boolean(), nullable=False))
    op.add_column('homeworks', sa.Column('notified_1h', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'notified_1h')
    op.drop_column('homeworks', 'notified_24h')
    # ### end Alembic commands ###
